//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드는 wsdl, 버전=4.0.30319.1에서 자동 생성되었습니다.
// 
namespace _1C.v4.CustomerVehicle {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerVehicleSoapBinding", Namespace="http://wa.dms.webservice/")]
    public partial class CustomerVehicle : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CustomerVehicleGetOperationCompleted;
        
        /// <remarks/>
        public CustomerVehicle(string url) 
        {
            this.Url = "http://192.168.32.2/rtr-atest/ws/customervehicle.1cws";
        }
        
        /// <remarks/>
        public event CustomerVehicleGetCompletedEventHandler CustomerVehicleGetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wa.dms.webservice/#CustomerVehicle:CustomerVehicleGet", RequestNamespace="http://wa.dms.webservice/", ResponseNamespace="http://wa.dms.webservice/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public CustomerVehicleGetResponse CustomerVehicleGet(CustomerVehicleGetRequest CustomerVehicleRequest) {
            object[] results = this.Invoke("CustomerVehicleGet", new object[] {
                        CustomerVehicleRequest});
            return ((CustomerVehicleGetResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCustomerVehicleGet(CustomerVehicleGetRequest CustomerVehicleRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CustomerVehicleGet", new object[] {
                        CustomerVehicleRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public CustomerVehicleGetResponse EndCustomerVehicleGet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerVehicleGetResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerVehicleGetAsync(CustomerVehicleGetRequest CustomerVehicleRequest) {
            this.CustomerVehicleGetAsync(CustomerVehicleRequest, null);
        }
        
        /// <remarks/>
        public void CustomerVehicleGetAsync(CustomerVehicleGetRequest CustomerVehicleRequest, object userState) {
            if ((this.CustomerVehicleGetOperationCompleted == null)) {
                this.CustomerVehicleGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerVehicleGetOperationCompleted);
            }
            this.InvokeAsync("CustomerVehicleGet", new object[] {
                        CustomerVehicleRequest}, this.CustomerVehicleGetOperationCompleted, userState);
        }
        
        private void OnCustomerVehicleGetOperationCompleted(object arg) {
            if ((this.CustomerVehicleGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerVehicleGetCompleted(this, new CustomerVehicleGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class CustomerVehicleGetRequest {
        
        private TransactionHeader transactionHeaderField;
        
        private CustomerVehicleGet customerVehicleGetField;
        
        /// <remarks/>
        public TransactionHeader TransactionHeader {
            get {
                return this.transactionHeaderField;
            }
            set {
                this.transactionHeaderField = value;
            }
        }
        
        /// <remarks/>
        public CustomerVehicleGet CustomerVehicleGet {
            get {
                return this.customerVehicleGetField;
            }
            set {
                this.customerVehicleGetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class TransactionHeader {
        
        private string countryIDField;
        
        private string distributorIDField;
        
        private string groupIDField;
        
        private string dealerIDField;
        
        private string dMSCodeField;
        
        private string dMSVersionField;
        
        private string dMSServerUrlField;
        
        private string documentVersionField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string transactionIdField;
        
        private System.DateTime transactionDateTimeUTCField;
        
        private System.DateTime transactionDateTimeLocalField;
        
        private string transactionTypeField;
        
        private string requestTypeField;
        
        private string requestPollingTokenField;
        
        private string venderTrackingCodeField;
        
        private string ineterfaceIDField;
        
        private string pollingTokenField;
        
        /// <remarks/>
        public string CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
            }
        }
        
        /// <remarks/>
        public string DistributorID {
            get {
                return this.distributorIDField;
            }
            set {
                this.distributorIDField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string DealerID {
            get {
                return this.dealerIDField;
            }
            set {
                this.dealerIDField = value;
            }
        }
        
        /// <remarks/>
        public string DMSCode {
            get {
                return this.dMSCodeField;
            }
            set {
                this.dMSCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DMSVersion {
            get {
                return this.dMSVersionField;
            }
            set {
                this.dMSVersionField = value;
            }
        }
        
        /// <remarks/>
        public string DMSServerUrl {
            get {
                return this.dMSServerUrlField;
            }
            set {
                this.dMSServerUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentVersion {
            get {
                return this.documentVersionField;
            }
            set {
                this.documentVersionField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDateTimeUTC {
            get {
                return this.transactionDateTimeUTCField;
            }
            set {
                this.transactionDateTimeUTCField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDateTimeLocal {
            get {
                return this.transactionDateTimeLocalField;
            }
            set {
                this.transactionDateTimeLocalField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestPollingToken {
            get {
                return this.requestPollingTokenField;
            }
            set {
                this.requestPollingTokenField = value;
            }
        }
        
        /// <remarks/>
        public string VenderTrackingCode {
            get {
                return this.venderTrackingCodeField;
            }
            set {
                this.venderTrackingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IneterfaceID {
            get {
                return this.ineterfaceIDField;
            }
            set {
                this.ineterfaceIDField = value;
            }
        }
        
        /// <remarks/>
        public string PollingToken {
            get {
                return this.pollingTokenField;
            }
            set {
                this.pollingTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class Campaign {
        
        private string campaignIDField;
        
        private string campaignDescriptionField;
        
        private string campaignPerformedField;
        
        /// <remarks/>
        public string CampaignID {
            get {
                return this.campaignIDField;
            }
            set {
                this.campaignIDField = value;
            }
        }
        
        /// <remarks/>
        public string CampaignDescription {
            get {
                return this.campaignDescriptionField;
            }
            set {
                this.campaignDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string CampaignPerformed {
            get {
                return this.campaignPerformedField;
            }
            set {
                this.campaignPerformedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class Vehicle {
        
        private string dMSVehicleNoField;
        
        private string vINField;
        
        private string stockNumberField;
        
        private string licensePlateNoField;
        
        private string makeField;
        
        private string modelCodeField;
        
        private string modelNameField;
        
        private string modelYearField;
        
        private string lastMileageField;
        
        private string colorField;
        
        private string vehicleTypeField;
        
        private string engineTypeField;
        
        private string fuelTypeField;
        
        private string cylindersField;
        
        private string trimField;
        
        private string fullModelNameField;
        
        private System.DateTime insuranceDateField;
        
        private System.DateTime dateInServiceField;
        
        private System.DateTime dateDeliveredField;
        
        private System.DateTime warrantyStartDateField;
        
        private string warrantyMonthsField;
        
        private string warrantyMilesField;
        
        private string licenseNumberField;
        
        private System.DateTime lastServiceDateField;
        
        private System.DateTime extendedWarrantyField;
        
        private string declinedJobField;
        
        private string pendingJobField;
        
        private string displayDescriptionField;
        
        private System.DateTime lastUModifiedDateTimeUTCField;
        
        private Campaign[] campaignsField;
        
        /// <remarks/>
        public string DMSVehicleNo {
            get {
                return this.dMSVehicleNoField;
            }
            set {
                this.dMSVehicleNoField = value;
            }
        }
        
        /// <remarks/>
        public string VIN {
            get {
                return this.vINField;
            }
            set {
                this.vINField = value;
            }
        }
        
        /// <remarks/>
        public string StockNumber {
            get {
                return this.stockNumberField;
            }
            set {
                this.stockNumberField = value;
            }
        }
        
        /// <remarks/>
        public string LicensePlateNo {
            get {
                return this.licensePlateNoField;
            }
            set {
                this.licensePlateNoField = value;
            }
        }
        
        /// <remarks/>
        public string Make {
            get {
                return this.makeField;
            }
            set {
                this.makeField = value;
            }
        }
        
        /// <remarks/>
        public string ModelCode {
            get {
                return this.modelCodeField;
            }
            set {
                this.modelCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
            }
        }
        
        /// <remarks/>
        public string ModelYear {
            get {
                return this.modelYearField;
            }
            set {
                this.modelYearField = value;
            }
        }
        
        /// <remarks/>
        public string LastMileage {
            get {
                return this.lastMileageField;
            }
            set {
                this.lastMileageField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public string VehicleType {
            get {
                return this.vehicleTypeField;
            }
            set {
                this.vehicleTypeField = value;
            }
        }
        
        /// <remarks/>
        public string EngineType {
            get {
                return this.engineTypeField;
            }
            set {
                this.engineTypeField = value;
            }
        }
        
        /// <remarks/>
        public string FuelType {
            get {
                return this.fuelTypeField;
            }
            set {
                this.fuelTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Cylinders {
            get {
                return this.cylindersField;
            }
            set {
                this.cylindersField = value;
            }
        }
        
        /// <remarks/>
        public string Trim {
            get {
                return this.trimField;
            }
            set {
                this.trimField = value;
            }
        }
        
        /// <remarks/>
        public string FullModelName {
            get {
                return this.fullModelNameField;
            }
            set {
                this.fullModelNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime InsuranceDate {
            get {
                return this.insuranceDateField;
            }
            set {
                this.insuranceDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateInService {
            get {
                return this.dateInServiceField;
            }
            set {
                this.dateInServiceField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateDelivered {
            get {
                return this.dateDeliveredField;
            }
            set {
                this.dateDeliveredField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime WarrantyStartDate {
            get {
                return this.warrantyStartDateField;
            }
            set {
                this.warrantyStartDateField = value;
            }
        }
        
        /// <remarks/>
        public string WarrantyMonths {
            get {
                return this.warrantyMonthsField;
            }
            set {
                this.warrantyMonthsField = value;
            }
        }
        
        /// <remarks/>
        public string WarrantyMiles {
            get {
                return this.warrantyMilesField;
            }
            set {
                this.warrantyMilesField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseNumber {
            get {
                return this.licenseNumberField;
            }
            set {
                this.licenseNumberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastServiceDate {
            get {
                return this.lastServiceDateField;
            }
            set {
                this.lastServiceDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExtendedWarranty {
            get {
                return this.extendedWarrantyField;
            }
            set {
                this.extendedWarrantyField = value;
            }
        }
        
        /// <remarks/>
        public string DeclinedJob {
            get {
                return this.declinedJobField;
            }
            set {
                this.declinedJobField = value;
            }
        }
        
        /// <remarks/>
        public string PendingJob {
            get {
                return this.pendingJobField;
            }
            set {
                this.pendingJobField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayDescription {
            get {
                return this.displayDescriptionField;
            }
            set {
                this.displayDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUModifiedDateTimeUTC {
            get {
                return this.lastUModifiedDateTimeUTCField;
            }
            set {
                this.lastUModifiedDateTimeUTCField = value;
            }
        }
        
        /// <remarks/>
        public Campaign[] Campaigns {
            get {
                return this.campaignsField;
            }
            set {
                this.campaignsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class CorporateInfo {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class SpecialMessage {
        
        private string messageField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class Address {
        
        private string addressTypeField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string countryField;
        
        private string zipCodeField;
        
        /// <remarks/>
        public string AddressType {
            get {
                return this.addressTypeField;
            }
            set {
                this.addressTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string ZipCode {
            get {
                return this.zipCodeField;
            }
            set {
                this.zipCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class Customer {
        
        private string customerInfoTypeField;
        
        private string dMSCustomerNoField;
        
        private string customerLastNameField;
        
        private string customerMiddleNameField;
        
        private string customerFirstNameField;
        
        private string customerFullNameField;
        
        private string salutationField;
        
        private string genderField;
        
        private string customerCardNoField;
        
        private string customerEmailField;
        
        private Address[] addressesField;
        
        private Contact[] contactsField;
        
        private SpecialMessage customerSpecialMessageField;
        
        private CorporateInfo[] corporateInfosField;
        
        /// <remarks/>
        public string CustomerInfoType {
            get {
                return this.customerInfoTypeField;
            }
            set {
                this.customerInfoTypeField = value;
            }
        }
        
        /// <remarks/>
        public string DMSCustomerNo {
            get {
                return this.dMSCustomerNoField;
            }
            set {
                this.dMSCustomerNoField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerLastName {
            get {
                return this.customerLastNameField;
            }
            set {
                this.customerLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerMiddleName {
            get {
                return this.customerMiddleNameField;
            }
            set {
                this.customerMiddleNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerFirstName {
            get {
                return this.customerFirstNameField;
            }
            set {
                this.customerFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerFullName {
            get {
                return this.customerFullNameField;
            }
            set {
                this.customerFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerCardNo {
            get {
                return this.customerCardNoField;
            }
            set {
                this.customerCardNoField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerEmail {
            get {
                return this.customerEmailField;
            }
            set {
                this.customerEmailField = value;
            }
        }
        
        /// <remarks/>
        public Address[] Addresses {
            get {
                return this.addressesField;
            }
            set {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        public Contact[] Contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
            }
        }
        
        /// <remarks/>
        public SpecialMessage CustomerSpecialMessage {
            get {
                return this.customerSpecialMessageField;
            }
            set {
                this.customerSpecialMessageField = value;
            }
        }
        
        /// <remarks/>
        public CorporateInfo[] CorporateInfos {
            get {
                return this.corporateInfosField;
            }
            set {
                this.corporateInfosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class Contact {
        
        private string contactTypeField;
        
        private string contactValueField;
        
        private string contactMethodYNField;
        
        /// <remarks/>
        public string ContactType {
            get {
                return this.contactTypeField;
            }
            set {
                this.contactTypeField = value;
            }
        }
        
        /// <remarks/>
        public string ContactValue {
            get {
                return this.contactValueField;
            }
            set {
                this.contactValueField = value;
            }
        }
        
        /// <remarks/>
        public string ContactMethodYN {
            get {
                return this.contactMethodYNField;
            }
            set {
                this.contactMethodYNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="CustomerVehicle", Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class CustomerVehicle1 {
        
        private Customer customerField;
        
        private Vehicle vehicleField;
        
        /// <remarks/>
        public Customer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public Vehicle Vehicle {
            get {
                return this.vehicleField;
            }
            set {
                this.vehicleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class Error {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class ResultMessage {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class CustomerVehicleGetResponse {
        
        private TransactionHeader transactionHeaderField;
        
        private ResultMessage resultMessageField;
        
        private Error[] errorsField;
        
        private CustomerVehicle1[] customerVehiclesField;
        
        /// <remarks/>
        public TransactionHeader TransactionHeader {
            get {
                return this.transactionHeaderField;
            }
            set {
                this.transactionHeaderField = value;
            }
        }
        
        /// <remarks/>
        public ResultMessage ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
            }
        }
        
        /// <remarks/>
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public CustomerVehicle1[] CustomerVehicles {
            get {
                return this.customerVehiclesField;
            }
            set {
                this.customerVehiclesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class VehicleGet {
        
        private string dMSVehicleNoField;
        
        private string vINField;
        
        private string lastSixVINField;
        
        private string licensePlateNoField;
        
        /// <remarks/>
        public string DMSVehicleNo {
            get {
                return this.dMSVehicleNoField;
            }
            set {
                this.dMSVehicleNoField = value;
            }
        }
        
        /// <remarks/>
        public string VIN {
            get {
                return this.vINField;
            }
            set {
                this.vINField = value;
            }
        }
        
        /// <remarks/>
        public string LastSixVIN {
            get {
                return this.lastSixVINField;
            }
            set {
                this.lastSixVINField = value;
            }
        }
        
        /// <remarks/>
        public string LicensePlateNo {
            get {
                return this.licensePlateNoField;
            }
            set {
                this.licensePlateNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class CustomerGet {
        
        private string dMSCustomerNoField;
        
        private string lastNameField;
        
        private string emailField;
        
        private string cardNoField;
        
        private Contact[] contactsField;
        
        /// <remarks/>
        public string DMSCustomerNo {
            get {
                return this.dMSCustomerNoField;
            }
            set {
                this.dMSCustomerNoField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string CardNo {
            get {
                return this.cardNoField;
            }
            set {
                this.cardNoField = value;
            }
        }
        
        /// <remarks/>
        public Contact[] Contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/CustomerVehicleGetRequest")]
    public partial class CustomerVehicleGet {
        
        private CustomerGet customerGetField;
        
        private VehicleGet vehicleGetField;
        
        /// <remarks/>
        public CustomerGet CustomerGet {
            get {
                return this.customerGetField;
            }
            set {
                this.customerGetField = value;
            }
        }
        
        /// <remarks/>
        public VehicleGet VehicleGet {
            get {
                return this.vehicleGetField;
            }
            set {
                this.vehicleGetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void CustomerVehicleGetCompletedEventHandler(object sender, CustomerVehicleGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerVehicleGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerVehicleGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustomerVehicleGetResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustomerVehicleGetResponse)(this.results[0]));
            }
        }
    }
}
