//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드는 wsdl, 버전=4.0.30319.1에서 자동 생성되었습니다.
// 
namespace _1C.v4.Job {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JobSoap", Namespace="http://wa.dms.webservice/")]
    public partial class Job : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback JobGetOperationCompleted;
        
        private System.Threading.SendOrPostCallback JobChangeOperationCompleted;
        
        /// <remarks/>
        public Job(string url)
        {
            this.Url = string.Format("{0}/v2/Common/Job.asmx", url);
        }
        
        /// <remarks/>
        public event JobGetCompletedEventHandler JobGetCompleted;
        
        /// <remarks/>
        public event JobChangeCompletedEventHandler JobChangeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wa.dms.webservice/JobGet", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("JobGetResponse", Namespace="http://wa.dms.webservice/JobGetResponse", IsNullable=true)]
        public JobGetResponse JobGet([System.Xml.Serialization.XmlElementAttribute(Namespace="http://wa.dms.webservice/JobGetRequest", IsNullable=true)] JobGetRequest JobGetRequest) {
            object[] results = this.Invoke("JobGet", new object[] {
                        JobGetRequest});
            return ((JobGetResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginJobGet(JobGetRequest JobGetRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("JobGet", new object[] {
                        JobGetRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public JobGetResponse EndJobGet(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((JobGetResponse)(results[0]));
        }
        
        /// <remarks/>
        public void JobGetAsync(JobGetRequest JobGetRequest) {
            this.JobGetAsync(JobGetRequest, null);
        }
        
        /// <remarks/>
        public void JobGetAsync(JobGetRequest JobGetRequest, object userState) {
            if ((this.JobGetOperationCompleted == null)) {
                this.JobGetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJobGetOperationCompleted);
            }
            this.InvokeAsync("JobGet", new object[] {
                        JobGetRequest}, this.JobGetOperationCompleted, userState);
        }
        
        private void OnJobGetOperationCompleted(object arg) {
            if ((this.JobGetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JobGetCompleted(this, new JobGetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wa.dms.webservice/JobChange", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("JobChangeResponse", Namespace="http://wa.dms.webservice/JobChangeResponse", IsNullable=true)]
        public JobChangeResponse JobChange([System.Xml.Serialization.XmlElementAttribute(Namespace="http://wa.dms.webservice/JobChangeRequest", IsNullable=true)] JobChangeRequest JobChangeRequest) {
            object[] results = this.Invoke("JobChange", new object[] {
                        JobChangeRequest});
            return ((JobChangeResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginJobChange(JobChangeRequest JobChangeRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("JobChange", new object[] {
                        JobChangeRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public JobChangeResponse EndJobChange(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((JobChangeResponse)(results[0]));
        }
        
        /// <remarks/>
        public void JobChangeAsync(JobChangeRequest JobChangeRequest) {
            this.JobChangeAsync(JobChangeRequest, null);
        }
        
        /// <remarks/>
        public void JobChangeAsync(JobChangeRequest JobChangeRequest, object userState) {
            if ((this.JobChangeOperationCompleted == null)) {
                this.JobChangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJobChangeOperationCompleted);
            }
            this.InvokeAsync("JobChange", new object[] {
                        JobChangeRequest}, this.JobChangeOperationCompleted, userState);
        }
        
        private void OnJobChangeOperationCompleted(object arg) {
            if ((this.JobChangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JobChangeCompleted(this, new JobChangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetRequest")]
    public partial class JobGetRequest {
        
        private TransactionHeader transactionHeaderField;
        
        private JobGet jobGetField;
        
        /// <remarks/>
        public TransactionHeader TransactionHeader {
            get {
                return this.transactionHeaderField;
            }
            set {
                this.transactionHeaderField = value;
            }
        }
        
        /// <remarks/>
        public JobGet JobGet {
            get {
                return this.jobGetField;
            }
            set {
                this.jobGetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetRequest")]
    public partial class TransactionHeader {
        
        private string countryIDField;
        
        private string distributorIDField;
        
        private string groupIDField;
        
        private string dealerIDField;
        
        private string dMSCodeField;
        
        private string dMSVersionField;
        
        private string dMSServerUrlField;
        
        private string documentVersionField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string transactionIdField;
        
        private System.DateTime transactionDateTimeUTCField;
        
        private System.DateTime transactionDateTimeLocalField;
        
        private string transactionTypeField;
        
        private string requestTypeField;
        
        private string requestPollingTokenField;
        
        private string venderTrackingCodeField;
        
        private string ineterfaceIDField;
        
        private string pollingTokenField;
        
        /// <remarks/>
        public string CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
            }
        }
        
        /// <remarks/>
        public string DistributorID {
            get {
                return this.distributorIDField;
            }
            set {
                this.distributorIDField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string DealerID {
            get {
                return this.dealerIDField;
            }
            set {
                this.dealerIDField = value;
            }
        }
        
        /// <remarks/>
        public string DMSCode {
            get {
                return this.dMSCodeField;
            }
            set {
                this.dMSCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DMSVersion {
            get {
                return this.dMSVersionField;
            }
            set {
                this.dMSVersionField = value;
            }
        }
        
        /// <remarks/>
        public string DMSServerUrl {
            get {
                return this.dMSServerUrlField;
            }
            set {
                this.dMSServerUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentVersion {
            get {
                return this.documentVersionField;
            }
            set {
                this.documentVersionField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDateTimeUTC {
            get {
                return this.transactionDateTimeUTCField;
            }
            set {
                this.transactionDateTimeUTCField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDateTimeLocal {
            get {
                return this.transactionDateTimeLocalField;
            }
            set {
                this.transactionDateTimeLocalField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestPollingToken {
            get {
                return this.requestPollingTokenField;
            }
            set {
                this.requestPollingTokenField = value;
            }
        }
        
        /// <remarks/>
        public string VenderTrackingCode {
            get {
                return this.venderTrackingCodeField;
            }
            set {
                this.venderTrackingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IneterfaceID {
            get {
                return this.ineterfaceIDField;
            }
            set {
                this.ineterfaceIDField = value;
            }
        }
        
        /// <remarks/>
        public string PollingToken {
            get {
                return this.pollingTokenField;
            }
            set {
                this.pollingTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Error", Namespace="http://wa.dms.webservice/JobChangeResponse")]
    public partial class Error1 {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ResultMessage", Namespace="http://wa.dms.webservice/JobChangeResponse")]
    public partial class ResultMessage1 {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="TransactionHeader", Namespace="http://wa.dms.webservice/JobChangeResponse")]
    public partial class TransactionHeader3 {
        
        private string countryIDField;
        
        private string distributorIDField;
        
        private string groupIDField;
        
        private string dealerIDField;
        
        private string dMSCodeField;
        
        private string dMSVersionField;
        
        private string dMSServerUrlField;
        
        private string documentVersionField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string transactionIdField;
        
        private System.DateTime transactionDateTimeUTCField;
        
        private System.DateTime transactionDateTimeLocalField;
        
        private string transactionTypeField;
        
        private string requestTypeField;
        
        private string requestPollingTokenField;
        
        private string venderTrackingCodeField;
        
        private string ineterfaceIDField;
        
        private string pollingTokenField;
        
        /// <remarks/>
        public string CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
            }
        }
        
        /// <remarks/>
        public string DistributorID {
            get {
                return this.distributorIDField;
            }
            set {
                this.distributorIDField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string DealerID {
            get {
                return this.dealerIDField;
            }
            set {
                this.dealerIDField = value;
            }
        }
        
        /// <remarks/>
        public string DMSCode {
            get {
                return this.dMSCodeField;
            }
            set {
                this.dMSCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DMSVersion {
            get {
                return this.dMSVersionField;
            }
            set {
                this.dMSVersionField = value;
            }
        }
        
        /// <remarks/>
        public string DMSServerUrl {
            get {
                return this.dMSServerUrlField;
            }
            set {
                this.dMSServerUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentVersion {
            get {
                return this.documentVersionField;
            }
            set {
                this.documentVersionField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDateTimeUTC {
            get {
                return this.transactionDateTimeUTCField;
            }
            set {
                this.transactionDateTimeUTCField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDateTimeLocal {
            get {
                return this.transactionDateTimeLocalField;
            }
            set {
                this.transactionDateTimeLocalField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestPollingToken {
            get {
                return this.requestPollingTokenField;
            }
            set {
                this.requestPollingTokenField = value;
            }
        }
        
        /// <remarks/>
        public string VenderTrackingCode {
            get {
                return this.venderTrackingCodeField;
            }
            set {
                this.venderTrackingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IneterfaceID {
            get {
                return this.ineterfaceIDField;
            }
            set {
                this.ineterfaceIDField = value;
            }
        }
        
        /// <remarks/>
        public string PollingToken {
            get {
                return this.pollingTokenField;
            }
            set {
                this.pollingTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobChangeResponse")]
    public partial class JobChangeResponse {
        
        private TransactionHeader3 transactionHeaderField;
        
        private ResultMessage1 resultMessageField;
        
        private Error1[] errorsField;
        
        /// <remarks/>
        public TransactionHeader3 TransactionHeader {
            get {
                return this.transactionHeaderField;
            }
            set {
                this.transactionHeaderField = value;
            }
        }
        
        /// <remarks/>
        public ResultMessage1 ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
            }
        }
        
        /// <remarks/>
        public Error1[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="JobComment", Namespace="http://wa.dms.webservice/JobChangeRequest")]
    public partial class JobComment1 {
        
        private string actualWorkHourField;
        
        private string subStatusField;
        
        /// <remarks/>
        public string ActualWorkHour {
            get {
                return this.actualWorkHourField;
            }
            set {
                this.actualWorkHourField = value;
            }
        }
        
        /// <remarks/>
        public string SubStatus {
            get {
                return this.subStatusField;
            }
            set {
                this.subStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="ActualTimeLog", Namespace="http://wa.dms.webservice/JobChangeRequest")]
    public partial class ActualTimeLog1 {
        
        private System.DateTime startDateTimeLocalField;
        
        private System.DateTime endDateTimeLocalField;
        
        private string tCEmployeeIDField;
        
        private string tCEmployeeNameField;
        
        private string statusField;
        
        private string pauseReasonCodeField;
        
        private string pauseReasonCommentField;
        
        /// <remarks/>
        public System.DateTime StartDateTimeLocal {
            get {
                return this.startDateTimeLocalField;
            }
            set {
                this.startDateTimeLocalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDateTimeLocal {
            get {
                return this.endDateTimeLocalField;
            }
            set {
                this.endDateTimeLocalField = value;
            }
        }
        
        /// <remarks/>
        public string TCEmployeeID {
            get {
                return this.tCEmployeeIDField;
            }
            set {
                this.tCEmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string TCEmployeeName {
            get {
                return this.tCEmployeeNameField;
            }
            set {
                this.tCEmployeeNameField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string PauseReasonCode {
            get {
                return this.pauseReasonCodeField;
            }
            set {
                this.pauseReasonCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PauseReasonComment {
            get {
                return this.pauseReasonCommentField;
            }
            set {
                this.pauseReasonCommentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Technician", Namespace="http://wa.dms.webservice/JobChangeRequest")]
    public partial class Technician1 {
        
        private string tCEmployeeIDField;
        
        private string tCEmployeeNameField;
        
        /// <remarks/>
        public string TCEmployeeID {
            get {
                return this.tCEmployeeIDField;
            }
            set {
                this.tCEmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string TCEmployeeName {
            get {
                return this.tCEmployeeNameField;
            }
            set {
                this.tCEmployeeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="JobLog", Namespace="http://wa.dms.webservice/JobChangeRequest")]
    public partial class JobLog1 {
        
        private string logTypeField;
        
        private string stallField;
        
        private string dMSJobStatusField;
        
        private string estimatedLaborHourField;
        
        private System.DateTime scheduledDateTimeFromLocalField;
        
        private System.DateTime scheduledDateTimeToLocalField;
        
        private Technician1[] techniciansField;
        
        private ActualTimeLog1[] actualTimeLogsField;
        
        private JobComment1[] jobCommentsField;
        
        /// <remarks/>
        public string LogType {
            get {
                return this.logTypeField;
            }
            set {
                this.logTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Stall {
            get {
                return this.stallField;
            }
            set {
                this.stallField = value;
            }
        }
        
        /// <remarks/>
        public string DMSJobStatus {
            get {
                return this.dMSJobStatusField;
            }
            set {
                this.dMSJobStatusField = value;
            }
        }
        
        /// <remarks/>
        public string EstimatedLaborHour {
            get {
                return this.estimatedLaborHourField;
            }
            set {
                this.estimatedLaborHourField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ScheduledDateTimeFromLocal {
            get {
                return this.scheduledDateTimeFromLocalField;
            }
            set {
                this.scheduledDateTimeFromLocalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ScheduledDateTimeToLocal {
            get {
                return this.scheduledDateTimeToLocalField;
            }
            set {
                this.scheduledDateTimeToLocalField = value;
            }
        }
        
        /// <remarks/>
        public Technician1[] Technicians {
            get {
                return this.techniciansField;
            }
            set {
                this.techniciansField = value;
            }
        }
        
        /// <remarks/>
        public ActualTimeLog1[] ActualTimeLogs {
            get {
                return this.actualTimeLogsField;
            }
            set {
                this.actualTimeLogsField = value;
            }
        }
        
        /// <remarks/>
        public JobComment1[] JobComments {
            get {
                return this.jobCommentsField;
            }
            set {
                this.jobCommentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="OPCode", Namespace="http://wa.dms.webservice/JobChangeRequest")]
    public partial class OPCode1 {
        
        private string codeField;
        
        private string descriptionField;
        
        private string estimatedHoursField;
        
        private string actualHoursField;
        
        private string skillLevelField;
        
        private Description1[] descriptionsField;
        
        private Cause1[] causesField;
        
        private Correction1[] correctionsField;
        
        private Comment1[] commentsField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string EstimatedHours {
            get {
                return this.estimatedHoursField;
            }
            set {
                this.estimatedHoursField = value;
            }
        }
        
        /// <remarks/>
        public string ActualHours {
            get {
                return this.actualHoursField;
            }
            set {
                this.actualHoursField = value;
            }
        }
        
        /// <remarks/>
        public string SkillLevel {
            get {
                return this.skillLevelField;
            }
            set {
                this.skillLevelField = value;
            }
        }
        
        /// <remarks/>
        public Description1[] Descriptions {
            get {
                return this.descriptionsField;
            }
            set {
                this.descriptionsField = value;
            }
        }
        
        /// <remarks/>
        public Cause1[] Causes {
            get {
                return this.causesField;
            }
            set {
                this.causesField = value;
            }
        }
        
        /// <remarks/>
        public Correction1[] Corrections {
            get {
                return this.correctionsField;
            }
            set {
                this.correctionsField = value;
            }
        }
        
        /// <remarks/>
        public Comment1[] Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Description", Namespace="http://wa.dms.webservice/JobChangeRequest")]
    public partial class Description1 {
        
        private string sequenceNumberField;
        
        private string descriptionCommentField;
        
        /// <remarks/>
        public string SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptionComment {
            get {
                return this.descriptionCommentField;
            }
            set {
                this.descriptionCommentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Cause", Namespace="http://wa.dms.webservice/JobChangeRequest")]
    public partial class Cause1 {
        
        private string sequenceNumberField;
        
        private string commentField;
        
        private string causeLaborOpCodeField;
        
        /// <remarks/>
        public string SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string CauseLaborOpCode {
            get {
                return this.causeLaborOpCodeField;
            }
            set {
                this.causeLaborOpCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Correction", Namespace="http://wa.dms.webservice/JobChangeRequest")]
    public partial class Correction1 {
        
        private string sequenceNumberField;
        
        private string commentField;
        
        private string correctionLaborOpCodeField;
        
        /// <remarks/>
        public string SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string CorrectionLaborOpCode {
            get {
                return this.correctionLaborOpCodeField;
            }
            set {
                this.correctionLaborOpCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Comment", Namespace="http://wa.dms.webservice/JobChangeRequest")]
    public partial class Comment1 {
        
        private string sequenceNumberField;
        
        private string descriptionCommentField;
        
        /// <remarks/>
        public string SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptionComment {
            get {
                return this.descriptionCommentField;
            }
            set {
                this.descriptionCommentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobChangeRequest")]
    public partial class JobChange {
        
        private string dMSJobNoField;
        
        private string dMSRONoField;
        
        private string dMSAppointmentNoField;
        
        private string serviceLineNumberField;
        
        private string estimatedHoursField;
        
        private string actualHoursField;
        
        private string skillLevelField;
        
        private Description1[] descriptionsField;
        
        private Cause1[] causesField;
        
        private Correction1[] correctionsField;
        
        private Comment1[] commentsField;
        
        private OPCode1[] oPCodesField;
        
        private JobLog1[] jobLogsField;
        
        /// <remarks/>
        public string DMSJobNo {
            get {
                return this.dMSJobNoField;
            }
            set {
                this.dMSJobNoField = value;
            }
        }
        
        /// <remarks/>
        public string DMSRONo {
            get {
                return this.dMSRONoField;
            }
            set {
                this.dMSRONoField = value;
            }
        }
        
        /// <remarks/>
        public string DMSAppointmentNo {
            get {
                return this.dMSAppointmentNoField;
            }
            set {
                this.dMSAppointmentNoField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceLineNumber {
            get {
                return this.serviceLineNumberField;
            }
            set {
                this.serviceLineNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EstimatedHours {
            get {
                return this.estimatedHoursField;
            }
            set {
                this.estimatedHoursField = value;
            }
        }
        
        /// <remarks/>
        public string ActualHours {
            get {
                return this.actualHoursField;
            }
            set {
                this.actualHoursField = value;
            }
        }
        
        /// <remarks/>
        public string SkillLevel {
            get {
                return this.skillLevelField;
            }
            set {
                this.skillLevelField = value;
            }
        }
        
        /// <remarks/>
        public Description1[] Descriptions {
            get {
                return this.descriptionsField;
            }
            set {
                this.descriptionsField = value;
            }
        }
        
        /// <remarks/>
        public Cause1[] Causes {
            get {
                return this.causesField;
            }
            set {
                this.causesField = value;
            }
        }
        
        /// <remarks/>
        public Correction1[] Corrections {
            get {
                return this.correctionsField;
            }
            set {
                this.correctionsField = value;
            }
        }
        
        /// <remarks/>
        public Comment1[] Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public OPCode1[] OPCodes {
            get {
                return this.oPCodesField;
            }
            set {
                this.oPCodesField = value;
            }
        }
        
        /// <remarks/>
        public JobLog1[] JobLogs {
            get {
                return this.jobLogsField;
            }
            set {
                this.jobLogsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="TransactionHeader", Namespace="http://wa.dms.webservice/JobChangeRequest")]
    public partial class TransactionHeader2 {
        
        private string countryIDField;
        
        private string distributorIDField;
        
        private string groupIDField;
        
        private string dealerIDField;
        
        private string dMSCodeField;
        
        private string dMSVersionField;
        
        private string dMSServerUrlField;
        
        private string documentVersionField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string transactionIdField;
        
        private System.DateTime transactionDateTimeUTCField;
        
        private System.DateTime transactionDateTimeLocalField;
        
        private string transactionTypeField;
        
        private string requestTypeField;
        
        private string requestPollingTokenField;
        
        private string venderTrackingCodeField;
        
        private string ineterfaceIDField;
        
        private string pollingTokenField;
        
        /// <remarks/>
        public string CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
            }
        }
        
        /// <remarks/>
        public string DistributorID {
            get {
                return this.distributorIDField;
            }
            set {
                this.distributorIDField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string DealerID {
            get {
                return this.dealerIDField;
            }
            set {
                this.dealerIDField = value;
            }
        }
        
        /// <remarks/>
        public string DMSCode {
            get {
                return this.dMSCodeField;
            }
            set {
                this.dMSCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DMSVersion {
            get {
                return this.dMSVersionField;
            }
            set {
                this.dMSVersionField = value;
            }
        }
        
        /// <remarks/>
        public string DMSServerUrl {
            get {
                return this.dMSServerUrlField;
            }
            set {
                this.dMSServerUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentVersion {
            get {
                return this.documentVersionField;
            }
            set {
                this.documentVersionField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDateTimeUTC {
            get {
                return this.transactionDateTimeUTCField;
            }
            set {
                this.transactionDateTimeUTCField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDateTimeLocal {
            get {
                return this.transactionDateTimeLocalField;
            }
            set {
                this.transactionDateTimeLocalField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestPollingToken {
            get {
                return this.requestPollingTokenField;
            }
            set {
                this.requestPollingTokenField = value;
            }
        }
        
        /// <remarks/>
        public string VenderTrackingCode {
            get {
                return this.venderTrackingCodeField;
            }
            set {
                this.venderTrackingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IneterfaceID {
            get {
                return this.ineterfaceIDField;
            }
            set {
                this.ineterfaceIDField = value;
            }
        }
        
        /// <remarks/>
        public string PollingToken {
            get {
                return this.pollingTokenField;
            }
            set {
                this.pollingTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobChangeRequest")]
    public partial class JobChangeRequest {
        
        private TransactionHeader2 transactionHeaderField;
        
        private JobChange jobChangeField;
        
        /// <remarks/>
        public TransactionHeader2 TransactionHeader {
            get {
                return this.transactionHeaderField;
            }
            set {
                this.transactionHeaderField = value;
            }
        }
        
        /// <remarks/>
        public JobChange JobChange {
            get {
                return this.jobChangeField;
            }
            set {
                this.jobChangeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class JobComment {
        
        private string actualWorkHourField;
        
        private string subStatusField;
        
        /// <remarks/>
        public string ActualWorkHour {
            get {
                return this.actualWorkHourField;
            }
            set {
                this.actualWorkHourField = value;
            }
        }
        
        /// <remarks/>
        public string SubStatus {
            get {
                return this.subStatusField;
            }
            set {
                this.subStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class ActualTimeLog {
        
        private System.DateTime startDateTimeLocalField;
        
        private System.DateTime endDateTimeLocalField;
        
        private string tCEmployeeIDField;
        
        private string tCEmployeeNameField;
        
        private string statusField;
        
        private string pauseReasonCodeField;
        
        private string pauseReasonCommentField;
        
        /// <remarks/>
        public System.DateTime StartDateTimeLocal {
            get {
                return this.startDateTimeLocalField;
            }
            set {
                this.startDateTimeLocalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndDateTimeLocal {
            get {
                return this.endDateTimeLocalField;
            }
            set {
                this.endDateTimeLocalField = value;
            }
        }
        
        /// <remarks/>
        public string TCEmployeeID {
            get {
                return this.tCEmployeeIDField;
            }
            set {
                this.tCEmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string TCEmployeeName {
            get {
                return this.tCEmployeeNameField;
            }
            set {
                this.tCEmployeeNameField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string PauseReasonCode {
            get {
                return this.pauseReasonCodeField;
            }
            set {
                this.pauseReasonCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PauseReasonComment {
            get {
                return this.pauseReasonCommentField;
            }
            set {
                this.pauseReasonCommentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class Technician {
        
        private string tCEmployeeIDField;
        
        private string tCEmployeeNameField;
        
        /// <remarks/>
        public string TCEmployeeID {
            get {
                return this.tCEmployeeIDField;
            }
            set {
                this.tCEmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        public string TCEmployeeName {
            get {
                return this.tCEmployeeNameField;
            }
            set {
                this.tCEmployeeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class JobLog {
        
        private string logTypeField;
        
        private string stallField;
        
        private string dMSJobStatusField;
        
        private string estimatedLaborHourField;
        
        private System.DateTime scheduledDateTimeFromLocalField;
        
        private System.DateTime scheduledDateTimeToLocalField;
        
        private Technician[] techniciansField;
        
        private ActualTimeLog[] actualTimeLogsField;
        
        private JobComment[] jobCommentsField;
        
        /// <remarks/>
        public string LogType {
            get {
                return this.logTypeField;
            }
            set {
                this.logTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Stall {
            get {
                return this.stallField;
            }
            set {
                this.stallField = value;
            }
        }
        
        /// <remarks/>
        public string DMSJobStatus {
            get {
                return this.dMSJobStatusField;
            }
            set {
                this.dMSJobStatusField = value;
            }
        }
        
        /// <remarks/>
        public string EstimatedLaborHour {
            get {
                return this.estimatedLaborHourField;
            }
            set {
                this.estimatedLaborHourField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ScheduledDateTimeFromLocal {
            get {
                return this.scheduledDateTimeFromLocalField;
            }
            set {
                this.scheduledDateTimeFromLocalField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ScheduledDateTimeToLocal {
            get {
                return this.scheduledDateTimeToLocalField;
            }
            set {
                this.scheduledDateTimeToLocalField = value;
            }
        }
        
        /// <remarks/>
        public Technician[] Technicians {
            get {
                return this.techniciansField;
            }
            set {
                this.techniciansField = value;
            }
        }
        
        /// <remarks/>
        public ActualTimeLog[] ActualTimeLogs {
            get {
                return this.actualTimeLogsField;
            }
            set {
                this.actualTimeLogsField = value;
            }
        }
        
        /// <remarks/>
        public JobComment[] JobComments {
            get {
                return this.jobCommentsField;
            }
            set {
                this.jobCommentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class OPCode {
        
        private string codeField;
        
        private string descriptionField;
        
        private string estimatedHoursField;
        
        private string actualHoursField;
        
        private string skillLevelField;
        
        private Description[] descriptionsField;
        
        private Cause[] causesField;
        
        private Correction[] correctionsField;
        
        private Comment[] commentsField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string EstimatedHours {
            get {
                return this.estimatedHoursField;
            }
            set {
                this.estimatedHoursField = value;
            }
        }
        
        /// <remarks/>
        public string ActualHours {
            get {
                return this.actualHoursField;
            }
            set {
                this.actualHoursField = value;
            }
        }
        
        /// <remarks/>
        public string SkillLevel {
            get {
                return this.skillLevelField;
            }
            set {
                this.skillLevelField = value;
            }
        }
        
        /// <remarks/>
        public Description[] Descriptions {
            get {
                return this.descriptionsField;
            }
            set {
                this.descriptionsField = value;
            }
        }
        
        /// <remarks/>
        public Cause[] Causes {
            get {
                return this.causesField;
            }
            set {
                this.causesField = value;
            }
        }
        
        /// <remarks/>
        public Correction[] Corrections {
            get {
                return this.correctionsField;
            }
            set {
                this.correctionsField = value;
            }
        }
        
        /// <remarks/>
        public Comment[] Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class Description {
        
        private string sequenceNumberField;
        
        private string descriptionCommentField;
        
        /// <remarks/>
        public string SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptionComment {
            get {
                return this.descriptionCommentField;
            }
            set {
                this.descriptionCommentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class Cause {
        
        private string sequenceNumberField;
        
        private string commentField;
        
        private string causeLaborOpCodeField;
        
        /// <remarks/>
        public string SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string CauseLaborOpCode {
            get {
                return this.causeLaborOpCodeField;
            }
            set {
                this.causeLaborOpCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class Correction {
        
        private string sequenceNumberField;
        
        private string commentField;
        
        private string correctionLaborOpCodeField;
        
        /// <remarks/>
        public string SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string CorrectionLaborOpCode {
            get {
                return this.correctionLaborOpCodeField;
            }
            set {
                this.correctionLaborOpCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class Comment {
        
        private string sequenceNumberField;
        
        private string descriptionCommentField;
        
        /// <remarks/>
        public string SequenceNumber {
            get {
                return this.sequenceNumberField;
            }
            set {
                this.sequenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string DescriptionComment {
            get {
                return this.descriptionCommentField;
            }
            set {
                this.descriptionCommentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class ManagementFields {
        
        private System.DateTime createDateTimeUTCField;
        
        private System.DateTime lastModifiedDateTimeUTCField;
        
        /// <remarks/>
        public System.DateTime CreateDateTimeUTC {
            get {
                return this.createDateTimeUTCField;
            }
            set {
                this.createDateTimeUTCField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastModifiedDateTimeUTC {
            get {
                return this.lastModifiedDateTimeUTCField;
            }
            set {
                this.lastModifiedDateTimeUTCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Job", Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class Job1 {
        
        private string dMSJobNoField;
        
        private string dMSRONoField;
        
        private string dMSAppointmentNoField;
        
        private string serviceLineNumberField;
        
        private string estimatedHoursField;
        
        private string actualHoursField;
        
        private string skillLevelField;
        
        private ManagementFields managementFieldsField;
        
        private Description[] descriptionsField;
        
        private Cause[] causesField;
        
        private Correction[] correctionsField;
        
        private Comment[] commentsField;
        
        private OPCode[] oPCodesField;
        
        private JobLog[] jobLogsField;
        
        /// <remarks/>
        public string DMSJobNo {
            get {
                return this.dMSJobNoField;
            }
            set {
                this.dMSJobNoField = value;
            }
        }
        
        /// <remarks/>
        public string DMSRONo {
            get {
                return this.dMSRONoField;
            }
            set {
                this.dMSRONoField = value;
            }
        }
        
        /// <remarks/>
        public string DMSAppointmentNo {
            get {
                return this.dMSAppointmentNoField;
            }
            set {
                this.dMSAppointmentNoField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceLineNumber {
            get {
                return this.serviceLineNumberField;
            }
            set {
                this.serviceLineNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EstimatedHours {
            get {
                return this.estimatedHoursField;
            }
            set {
                this.estimatedHoursField = value;
            }
        }
        
        /// <remarks/>
        public string ActualHours {
            get {
                return this.actualHoursField;
            }
            set {
                this.actualHoursField = value;
            }
        }
        
        /// <remarks/>
        public string SkillLevel {
            get {
                return this.skillLevelField;
            }
            set {
                this.skillLevelField = value;
            }
        }
        
        /// <remarks/>
        public ManagementFields ManagementFields {
            get {
                return this.managementFieldsField;
            }
            set {
                this.managementFieldsField = value;
            }
        }
        
        /// <remarks/>
        public Description[] Descriptions {
            get {
                return this.descriptionsField;
            }
            set {
                this.descriptionsField = value;
            }
        }
        
        /// <remarks/>
        public Cause[] Causes {
            get {
                return this.causesField;
            }
            set {
                this.causesField = value;
            }
        }
        
        /// <remarks/>
        public Correction[] Corrections {
            get {
                return this.correctionsField;
            }
            set {
                this.correctionsField = value;
            }
        }
        
        /// <remarks/>
        public Comment[] Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        public OPCode[] OPCodes {
            get {
                return this.oPCodesField;
            }
            set {
                this.oPCodesField = value;
            }
        }
        
        /// <remarks/>
        public JobLog[] JobLogs {
            get {
                return this.jobLogsField;
            }
            set {
                this.jobLogsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class Error {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class ResultMessage {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="TransactionHeader", Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class TransactionHeader1 {
        
        private string countryIDField;
        
        private string distributorIDField;
        
        private string groupIDField;
        
        private string dealerIDField;
        
        private string dMSCodeField;
        
        private string dMSVersionField;
        
        private string dMSServerUrlField;
        
        private string documentVersionField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string transactionIdField;
        
        private System.DateTime transactionDateTimeUTCField;
        
        private System.DateTime transactionDateTimeLocalField;
        
        private string transactionTypeField;
        
        private string requestTypeField;
        
        private string requestPollingTokenField;
        
        private string venderTrackingCodeField;
        
        private string ineterfaceIDField;
        
        private string pollingTokenField;
        
        /// <remarks/>
        public string CountryID {
            get {
                return this.countryIDField;
            }
            set {
                this.countryIDField = value;
            }
        }
        
        /// <remarks/>
        public string DistributorID {
            get {
                return this.distributorIDField;
            }
            set {
                this.distributorIDField = value;
            }
        }
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string DealerID {
            get {
                return this.dealerIDField;
            }
            set {
                this.dealerIDField = value;
            }
        }
        
        /// <remarks/>
        public string DMSCode {
            get {
                return this.dMSCodeField;
            }
            set {
                this.dMSCodeField = value;
            }
        }
        
        /// <remarks/>
        public string DMSVersion {
            get {
                return this.dMSVersionField;
            }
            set {
                this.dMSVersionField = value;
            }
        }
        
        /// <remarks/>
        public string DMSServerUrl {
            get {
                return this.dMSServerUrlField;
            }
            set {
                this.dMSServerUrlField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentVersion {
            get {
                return this.documentVersionField;
            }
            set {
                this.documentVersionField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDateTimeUTC {
            get {
                return this.transactionDateTimeUTCField;
            }
            set {
                this.transactionDateTimeUTCField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransactionDateTimeLocal {
            get {
                return this.transactionDateTimeLocalField;
            }
            set {
                this.transactionDateTimeLocalField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RequestPollingToken {
            get {
                return this.requestPollingTokenField;
            }
            set {
                this.requestPollingTokenField = value;
            }
        }
        
        /// <remarks/>
        public string VenderTrackingCode {
            get {
                return this.venderTrackingCodeField;
            }
            set {
                this.venderTrackingCodeField = value;
            }
        }
        
        /// <remarks/>
        public string IneterfaceID {
            get {
                return this.ineterfaceIDField;
            }
            set {
                this.ineterfaceIDField = value;
            }
        }
        
        /// <remarks/>
        public string PollingToken {
            get {
                return this.pollingTokenField;
            }
            set {
                this.pollingTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetResponse")]
    public partial class JobGetResponse {
        
        private TransactionHeader1 transactionHeaderField;
        
        private ResultMessage resultMessageField;
        
        private Error[] errorsField;
        
        private Job1[] jobsField;
        
        /// <remarks/>
        public TransactionHeader1 TransactionHeader {
            get {
                return this.transactionHeaderField;
            }
            set {
                this.transactionHeaderField = value;
            }
        }
        
        /// <remarks/>
        public ResultMessage ResultMessage {
            get {
                return this.resultMessageField;
            }
            set {
                this.resultMessageField = value;
            }
        }
        
        /// <remarks/>
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public Job1[] Jobs {
            get {
                return this.jobsField;
            }
            set {
                this.jobsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wa.dms.webservice/JobGetRequest")]
    public partial class JobGet {
        
        private string dMSAppointmentNoField;
        
        private string dMSRONoField;
        
        private string dMSJobNoField;
        
        private string dMSJobStatusField;
        
        private System.Nullable<System.DateTime> scheduledDateTimeFromLocalField;
        
        private System.Nullable<System.DateTime> scheduledDateTimeToLocalField;
        
        private System.Nullable<System.DateTime> lastModifiedDateTimeFromUTCField;
        
        private System.Nullable<System.DateTime> lastModifiedDateTimeToUTCField;
        
        /// <remarks/>
        public string DMSAppointmentNo {
            get {
                return this.dMSAppointmentNoField;
            }
            set {
                this.dMSAppointmentNoField = value;
            }
        }
        
        /// <remarks/>
        public string DMSRONo {
            get {
                return this.dMSRONoField;
            }
            set {
                this.dMSRONoField = value;
            }
        }
        
        /// <remarks/>
        public string DMSJobNo {
            get {
                return this.dMSJobNoField;
            }
            set {
                this.dMSJobNoField = value;
            }
        }
        
        /// <remarks/>
        public string DMSJobStatus {
            get {
                return this.dMSJobStatusField;
            }
            set {
                this.dMSJobStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ScheduledDateTimeFromLocal {
            get {
                return this.scheduledDateTimeFromLocalField;
            }
            set {
                this.scheduledDateTimeFromLocalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ScheduledDateTimeToLocal {
            get {
                return this.scheduledDateTimeToLocalField;
            }
            set {
                this.scheduledDateTimeToLocalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastModifiedDateTimeFromUTC {
            get {
                return this.lastModifiedDateTimeFromUTCField;
            }
            set {
                this.lastModifiedDateTimeFromUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastModifiedDateTimeToUTC {
            get {
                return this.lastModifiedDateTimeToUTCField;
            }
            set {
                this.lastModifiedDateTimeToUTCField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void JobGetCompletedEventHandler(object sender, JobGetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JobGetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JobGetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JobGetResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JobGetResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    public delegate void JobChangeCompletedEventHandler(object sender, JobChangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JobChangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JobChangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public JobChangeResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((JobChangeResponse)(this.results[0]));
            }
        }
    }
}
